version: "3.8"
services:
  web:
    image: bitcoinmessagetools-dev
    container_name: bitcoinmessagetools-dev
    build:
      context: web
      dockerfile: Dockerfile.dev
    volumes:
      - ./web/website/:/app/website
    ports:
      - 5000:5000
    healthcheck:
      test:
        [
          "CMD-SHELL",
          "bash",
          "-c",
          "curl",
          "-f",
          "http://localhost:5000/up"
        ]
      interval: 60s
      timeout: 30s
      retries: 3
      start_period: 5s
