version: "3.8"
services:
  web:
    image: bitcoinmessagetools-prod
    container_name: bitcoinmessagetools-prod
    build:
      context: web
      dockerfile: Dockerfile.prod
    restart: unless-stopped
    env_file:
      - web/.env
    networks:
      - bmt_network
  proxy:
    build:
      context: proxy
    restart: unless-stopped
    ports:
      - 80:80
    networks:
      - bmt_network
networks:
  bmt_network:
