version: "3.8"
services:
  web:
    build:
      context: web
      dockerfile: Dockerfile.prod
    restart: unless-stopped
    env_file:
      - web/.env
    networks:
      - flask_network
  proxy:
    build:
      context: proxy
    restart: unless-stopped
    ports:
      - 80:80
    networks:
      - flask_network
networks:
  flask_network:
