version: "3.8"
services:
  web:
    build:
      context: web
      dockerfile: Dockerfile
    restart: unless-stopped
    command: gunicorn --bind 0.0.0.0:5000 -w 3 run:app
    env_file:
      - web/.env
    networks:
      - flask_network
  proxy:
    build:
      context: proxy
    restart: unless-stopped
    ports:
      - 80:80
    networks:
      - flask_network
networks:
  flask_network:
