version: "3.8"
services:
  web:
    build:
      context: web
    command: python run.py run -h 0.0.0.0
    restart: unless-stopped
    volumes:
      - web/:/app/
    ports:
      - 5000:5000
    env_file:
      - web/.env.dev
    networks:
      - flask_network
  proxy:
    build:
      context: proxy
    restart: unless-stopped
    ports:
      - 80:80
    networks:
      - flask_network
networks:
  flask_network:
